### ISSUE TITLE
Latest Eheim Update 

### ISSUE THREAD

**Issue by Stiesel** [davidm-glitch/home-assistant-eheim-digital#20]
Hallo leider werden mit dem aktuellen Update keine Daten mehr übertragen,
![Screenshot_20240626_091705_Chrome](https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/75696888/1429d797-d316-462d-add1-e87e1bd527b7)

Hello, unfortunately with the current update no more data is transferred,

**Comment by Smarthome-Creator** [comment]
Schließe mich an.

**Comment by davidm-glitch** [comment]
Könnt ihr bitte mal die Logs hier posten?

**Comment by Stiesel** [comment]
`Logger: homeassistant.config_entries
Quelle: config_entries.py:594
Erstmals aufgetreten: 23:56:52 (3 Vorkommnisse)
Zuletzt protokolliert: 23:57:42

Error setting up entry 192.168.178.161 for eheim_digital
Traceback (most recent call last):
  File "/config/custom_components/eheim_digital/websocket.py", line 81, in connect_websocket
    self._websocket = await websockets.connect(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1120, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1102, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1005, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.178.161', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/__init__.py", line 22, in async_setup_entry
    devices = await websocket_client.fetch_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/websocket.py", line 117, in fetch_devices
    await self.connect_websocket()
  File "/config/custom_components/eheim_digital/websocket.py", line 99, in connect_websocket
    raise EheimDigitalWebSocketClientCommunicationError(
custom_components.eheim_digital.websocket.EheimDigitalWebSocketClientCommunicationError: Failed to connect to WebSocket: [Errno 113] Connect call failed ('192.168.178.161', 80)`

**Comment by Stiesel** [comment]
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.eheim_digital
Quelle: custom_components/eheim_digital/websocket.py:51
Integration: EHEIM Digital (Dokumentation, Probleme)
Erstmals aufgetreten: 23:45:29 (20 Vorkommnisse)
Zuletzt protokolliert: 23:57:29

Failed to reconnect after max retries`

**Comment by Stiesel** [comment]
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Quelle: custom_components/eheim_digital/sensor.py:166
Integration: EHEIM Digital (Dokumentation, Probleme)
Erstmals aufgetreten: 19:38:54 (21 Vorkommnisse)
Zuletzt protokolliert: 20:15:29

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/config/custom_components/eheim_digital/sensor.py", line 307, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 543, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/sensor.py", line 296, in native_value
    return self.entity_description.value_fn(self._sensor_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/sensor.py", line 166, in <lambda>
    value_fn=lambda data: round((int(data["isPH"]) / 10), 1),
                                     ~~~~^^^^^^^^
KeyError: 'isPH'`

**Comment by Stiesel** [comment]
`Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:914
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 15:42:51 (5 Vorkommnisse)
Zuletzt protokolliert: 20:14:58

Error adding entity sensor.eheim_reeflex_2410996_operating_time for domain sensor with platform eheim_digital
Error adding entity sensor.eheim_filter_1105346_operating_time for domain sensor with platform eheim_digital
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 914, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1355, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 543, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/sensor.py", line 296, in native_value
    return self.entity_description.value_fn(self._sensor_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/sensor.py", line 73, in <lambda>
    value_fn=lambda data: data.get("actualTime") / (1440 * 24),
                          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'`

**Comment by Stiesel** [comment]
`Logger: homeassistant.components.sensor
Quelle: components/sensor/__init__.py:732
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 15:40:51 (5 Vorkommnisse)
Zuletzt protokolliert: 20:14:55

Entity sensor.eheim_ph_14530908_kh_value (<class 'custom_components.eheim_digital.sensor.EheimSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('carbon_dioxide') it is using; expected one of ['ppm']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/davidm-glitch/home-assistant-eheim-digital/issues`

**Comment by Stiesel** [comment]
[Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Quelle: custom_components/eheim_digital/sensor.py:73
Integration: EHEIM Digital (Dokumentation, Probleme)
Erstmals aufgetreten: 15:42:51 (22 Vorkommnisse)
Zuletzt protokolliert: 20:14:50

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/config/custom_components/eheim_digital/sensor.py", line 307, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 543, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/sensor.py", line 296, in native_value
    return self.entity_description.value_fn(self._sensor_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/sensor.py", line 73, in <lambda>
    value_fn=lambda data: data.get("actualTime") / (1440 * 24),
                          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'](url)

**Comment by Stiesel** [comment]
`Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:729
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 15:42:51 (2 Vorkommnisse)
Zuletzt protokolliert: 20:12:10

eheim_digital: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 729, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1289, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 529, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 262, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 288, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/config/custom_components/eheim_digital/sensor.py", line 307, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1000, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1126, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1061, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 543, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/sensor.py", line 296, in native_value
    return self.entity_description.value_fn(self._sensor_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/sensor.py", line 73, in <lambda>
    value_fn=lambda data: data.get("actualTime") / (1440 * 24),
                          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'`

**Comment by Stiesel** [comment]
Sorry für die Anzahl der Post, wurde über das Handy hochgeladen, da ging es nicht besser

**Comment by Stiesel** [comment]
Der UVC-Kläger zieht jetzt die Daten des Filters, und der Filter die Daten des UVC-Klärers

![Screenshot_20240627_202226_Home Assistant](https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/75696888/04ca9b83-1190-40f6-9006-c0a0682ffd49)
![Screenshot_20240627_202233_Home Assistant](https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/75696888/8cdc8aa8-7907-4bf1-8e42-b0ab5f3c544d)

**Comment by davidm-glitch** [comment]
Ich habe nun auch meine Geräte aktualisiert, konnte aber kein solches Verhalten feststellen.

Habt ihr mal versucht die Integration zu löschen und erneut einzurichten? Die Zuordnung erfolgt eigentlich per Mac-Adresse, da sollte sich auch nichts dran geändert haben.

**Comment by Smarthome-Creator** [comment]
@davidm-glitch, bei mir hat sich nach dem Update die IP Adresse des Filters geändert, was ja eigentlich egal sein sollte, da ich den Filter über seinen DNS Namen eingerichtet hatte.

Das geht nun aktuell leider nicht mehr. Könnte verschiedene Ursachen haben, das letzte Update des Filters oder das letzte Update der Fritz!Box oder durch das letzte HA Update. Jedenfalls, wenn ich ihn wieder direkt über die IP einbinde bekomme ich wieder Daten.

**Comment by davidm-glitch** [comment]
Okay, also issue closed?

**Comment by Smarthome-Creator** [comment]
> Okay, also issue closed?

Also von meiner Seite her ja.
