### ISSUE TITLE
Connection cannot be established

### ISSUE THREAD

**Issue by Smarthome-Creator** [davidm-glitch/home-assistant-eheim-digital#7]
Hello @davidm-glitch , I wanted to test the integration and unfortunately I do not get a connection to the filter.
<img width="384" alt="Bildschirmfoto 2023-08-14 um 18 23 41" src="https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/61153058/f9e1c222-ec40-4471-8e2f-3ac0ceac39ae">

Error message from log:

2023-08-14 18:22:29.961 ERROR (MainThread) [custom_components.eheim_digital] Unexpected error fetching Eheim Digital Data Coordinator data: 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/coordinator.py", line 60, in async_update_data
    device = EheimDevice(device_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/devices.py", line 9, in __init__
    self._title = data.get("title")
                  ^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

and:

2023-08-14 18:24:00.081 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry X.X.X.X for eheim_digital
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/eheim_digital/websocket.py", line 31, in connect_websocket
    self._websocket = await websockets.connect(self._url) #pylint: disable=all
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/client.py", line 654, in __await_impl_timeout__
    async with asyncio_timeout(self.open_timeout):
  File "/usr/local/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/__init__.py", line 19, in async_setup_entry
    devices = await websocket_client.fetch_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eheim_digital/websocket.py", line 74, in fetch_devices
    await self.connect_websocket()
  File "/config/custom_components/eheim_digital/websocket.py", line 33, in connect_websocket
    raise EheimDigitalWebSocketClientCommunicationError(f"Failed to connect to WebSocket: {ex}") from ex
custom_components.eheim_digital.websocket.EheimDigitalWebSocketClientCommunicationError: Failed to connect to WebSocket:

BTW, great job!

**Comment by davidm-glitch** [comment]
Hi @Smarthome-Creator, thank you for sharing your issue. 
Be aware that this is still highly work in progress ;)

@jkhalil can you take a look at this?


EDIT: Ich sehe grad die Fehlermeldung in deinem Screenshot. Deutsch ist auch ok für mich ;)

**Comment by jkhalil** [comment]
Hi @Smarthome-Creator - 

This is in the middle of a refactor and doesn't necessarily work yet. :)

However! I'm actively working on getting to a point where we can release a testable version. 

Currently we have devices being added to HomeAssistant but sensors, switches, lights, or update functionality have not been implemented.

Hang tight and we should be updating soon for you to help us test. 😀

**Comment by davidm-glitch** [comment]
Development is ongoing, but this issue is fixed.
